### ISSUE TITLE
Set up test suite for OpenACC GPU code

### ISSUE THREAD

**Issue by sjsprecious** [NCAR/micm#136]
My current plan of OpenACC implementation for the chemistry solver is to add the directives to the original C++ code, which avoids the duplication of source code.

However, since now GPU and CPU share the same code base, how could I write a test suite to verify the OpenACC results, just like what we did for CPU and CUDA?

@mattldawson @K20shores do you have any ideas about this issue?

**Comment by mattldawson** [comment]
I'm not sure that it could be included in the automated tests, since we don't have access to GPUs for those, but if you compiled in OpenACC support and ran on Gust/Derecho I think the existing unit tests should test the OpenACC directives. @K20shores - what do you think?

**Comment by sjsprecious** [comment]
Thanks @mattldawson . I agree that we could write a unit test for the OpenACC code. But I think it is better to write a verification test like Qina did for CPU and CUDA, which will give me more confidence of the OpenACC implementation.

**Comment by mattldawson** [comment]
Hi @sjsprecious - I don't think you would actually have to write a unit test, I think the running the existing unit tests with OpenACC support compiled in should test the GPU code.

**Comment by mattldawson** [comment]
closing as we decided not to go with OpenACCC
