### ISSUE TITLE
Configuration format documentation

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#154]
Where should the documentation for the configuration data format exist?

We share a configuration format with [CAMP](https://github.com/open-atmos/camp) and Kyle recently created a dedicated repo to store the configuration format [here](https://github.com/open-atmos/CampConfiguration).

It would be nice not to have to repeat the documentation in multiple places, but where should it exist? (in this repo? in the CampConfiguration repo? somewhere else?)

**Comment by K20shores** [comment]
This will live in the open atmos configuration: https://github.com/open-atmos/MechanismConfiguration
