### ISSUE TITLE
Issues about building MICM on Casper

### ISSUE THREAD

**Issue by sjsprecious** [NCAR/micm#16]
I am trying to build MICM on Casper but encounter some issues. I need to manually revise the `CMakeLists.txt` file to resolve them:

- The `NETCDF_HOME` env variable is not defined on Casper and thus the NETCDF module can not be found even if I have loaded it in my environment. The `NETCDF` env variable is defined on Casper and seems to work the same as `NETCDF_HOME`. Can we add it to the search path?
https://github.com/NCAR/micm/blob/9fdec9c39f70e094fa3225366118cca50a9dcfee/CMakeLists.txt#L16

- The `lib` suffix in the search path should be changed to `include`. I am not sure why the container version still works since we are searching for header files here.
https://github.com/NCAR/micm/blob/9fdec9c39f70e094fa3225366118cca50a9dcfee/CMakeLists.txt#L44

**Comment by mattldawson** [comment]
Hi @sjsprecious

These are just the standard search paths. If they're not found here, you don't need to modify the CMakeLists.txt file, you can just set the paths in the call to cmake:
```
cmake -D NETCDF_INCLUDE_DIR=/path/to/netcdf/include \
      -D NETCDF_C_LIB=/path/to/libnetcdf \
      -D NETCDF_FORTRAN_LIB=/path/to/libnetcdff \
      -D JSON_INCLUDE_DIR=/path/to/jsonfortran/mod/files \
      -D JSON_LIB=/path/to/libjsonfortran \
      ..
```
Or you can set them in the CMake gui with:
```
ccmake ..
```
Or you can set the environment variables MICM looks for:
```
export NETCDF_HOME=/path/to/netcdf/home
export JSON_FORTRAN_HOME=/path/to/jsonfortran/home
```

By default, json-fortran includes the `.mod` files with the library in `/usr/local/jsonfortran-compiler-version/lib` on install. For example, in the container:
```
[root@668ce9b49fbb /]# ls /usr/local/jsonfortran-gnu-8.2.0/lib/
json_file_module.mod  json_parameters.mod        libjsonfortran.a       libjsonfortran.so.8.2.0
json_kinds.mod        json_string_utilities.mod  libjsonfortran.so      pkgconfig
json_module.mod       json_value_module.mod      libjsonfortran.so.8.2
```
