### ISSUE TITLE
Configurations with more species than those used in reactions

### ISSUE THREAD

**Issue by K20shores** [NCAR/micm#189]
Configurations that contain more species in a species file than are present in a reaction report a larger state size than the number of species in the reaction. Not sure if this is problematic.

For example, this configuration [micm.zip](https://github.com/NCAR/micm/files/12346193/micm.zip) and this program prints 100, but only 53 species are actually used in the reactions

```
#include <iostream>
#include <micm/configure/solver_config.hpp>
#include <fstream>
#include <sstream>
#include <filesystem>

namespace fs = std::filesystem;
using namespace micm;

int main(const int argc, const char *argv[])
{
    fs::path configDir = fs::path("micm");

    SolverConfig solverConfig;
    ConfigParseStatus status = solverConfig.ReadAndParse(configDir);

    SolverParameters solver_params = solverConfig.GetSolverParams();

    size_t nspecies = solver_params.system_.StateSize();

    std::cout << "Species: " << nspecies << std::endl;
}

```

Send warning that certain species are unused, and create the solver/state as if they had been excluded from the configuration.

**Comment by mattldawson** [comment]
also add `NumberOfGridCells()`, `NumberOfSpecies()` and `NumberOfProcesses()` to the `State`
