### ISSUE TITLE
Develop an abstract rate_constant_t type for rate constant calculations

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#2]

**Comment by AndrewJConley** [comment]
My thought is that the core is already present in src/rate_constant_functions.F90. If we combined the rate constant parameters and the rate constant functions so that the json could be used to construct rate constant function pointers, we'd have what we need for the abstract type.  But I'm not sure as to how the json file is read and the factory built to construct the runtime pointers to functions.

**Comment by mattldawson** [comment]
I will set up a driver that passes the json config data to a simplified `kinetics_t` type constructor. the simple `kinetics_t` type will only have data members and functions that are related to the rate constants (the other functions and data can remain the same as they currently are). and the `kinetics_t` constructor will use the `rate_constant_factory` to build the set of `rate_constant_t` objects.

**Comment by AndrewJConley** [comment]
The photodecomposition rate constants have significantly different sources of data and dependencies than the rate constants for chemical reactions.  This will be interesting.

**Comment by mattldawson** [comment]
Hi @AndrewJConley - I think the code is roughed in. It's in `etc/rate_constant_demo/`. (I already merged it into `micm/master` because I needed to fix a problem with the musica-core library in micm). Let me know if you have any questions about the setup and if this is what you were expecting. You should be able to build and run the code with:
```
cd micm/etc/rate_constant_demo
mkdir build
cd build
ccmake ..
make
./rate_constant_demo ../config.json
```

**Comment by AndrewJConley** [comment]
Stacy is working to bring the rate constants for photolysis into the form described here: https://docs.google.com/document/d/14vnBbO2_gBaKVMbymh2e0DwCHGas_zSZ0U9DB3nQnc0/edit?usp=sharing

**Comment by mattldawson** [comment]
draft rate constant type was created and used as a template in the photolysis code refactor. closing issue
