### ISSUE TITLE
Memory check failure for NVHPC compiler

### ISSUE THREAD

**Issue by sjsprecious** [NCAR/micm#243]
I ran the memory check for MICM on Derecho with the following module env:
```
  1) ncarenv/23.09 (S)   3) nvhpc/23.7            5) hdf5/1.12.2    7) cray-mpich/8.1.25   9) valgrind4hpc/2.12.11
  2) craype/2.7.20       4) ncarcompilers/1.0.0   6) netcdf/4.9.2   8) cray-mrnet/5.0.4   10) cmake/3.26.3
```
The memory test on Derecho's CPU with `nvhpc` compiler suggests two failures:
```
96% tests passed, 2 tests failed out of 54

Total Test time (real) = 158.77 sec

The following tests FAILED:
	 11 - troe_rate_constant (Failed)
	 12 - memcheck_troe_rate_constant (Failed)
```

**Comment by K20shores** [comment]
In #233 we learned that NVHPC seems to compute the troe rate constant with a different level of precision in a debug build in the class method as opposed to the calculation in the test. A difference is that the values are pulled from the class member variables vs written into the calculation by hand. There was no difference in the values, but still the level of precision  was different.

However, a release build did not have the difference of precision. No idea why. The resolution is to test an nvhpc build in our CI as a release version and ignore this failure with the debug build. At this point, this seems to be an internal compiler error and we will not investigate further
