### ISSUE TITLE
Emissions reaction can't handle products

### ISSUE THREAD

**Issue by K20shores** [NCAR/micm#331]
The [carbon_bond_5.zip](https://github.com/NCAR/micm/files/13189681/carbon_bond_5.zip) mechanism from music box contains products on every reaction, like emissions. Should we allow this? in #309 I am adding a warning to say this so that we can parse carbon bond 5, but the products will be ignored

**Comment by mattldawson** [comment]
This is actually a bug on the MusicBox Interactive side. I added an issue for this on that repo: https://github.com/NCAR/music-box-interactive-client/issues/108
