### ISSUE TITLE
Bad assignment to a matrix wipes out information.

### ISSUE THREAD

**Issue by K20shores** [NCAR/micm#333]
Suppose you have a micm state (https://github.com/NCAR/micm/blob/main/test/tutorial/test_openmp.cpp#L28-L34).

A proper assignment is this:

```
state.variables_[0] = { 1, 0, 0 }
```

If you leave off `[0]`, the assignment succeeds but leaves the `variables_` matrix in an invalid state with a size of zero.

**Comment by mattldawson** [comment]
This turned out to be specific to a set of three integer values, which end up being passed to the three argument Matrix constructor.
