### ISSUE TITLE
Change the name "linear_solver" to "lu_solve" for both CPU and GPU code

### ISSUE THREAD

**Issue by sjsprecious** [NCAR/micm#363]
As mentioned in this PR #358, the whole ODE solver (calculate Jacobian matrix, LU factorization, etc) could be treated as a **linear solver**. The code introduced in the PR #358 is the backward elimination based on the result of LU factorization. Calling it **linear_solver** is misleading and it is better to rename it to **cuda_lu_solve** for GPU code and **lu_solve** for CPU code everywhere.

**Comment by qinatan** [comment]
Should I make the name change to both CPU and GPU? Or GPU only? I would suggest I only make change on the GPU side since I am not familiar of the dependency of CPU code of this class.

**Comment by sjsprecious** [comment]
That sounds good. I think you could just focus on the GPU code after your PR is merged. I just assigned Matt to work on the CPU code if he had time.

**Comment by mattldawson** [comment]
I agree, but unless you have run out of issues, let's schedule these new tasks next sprint.

**Comment by mattldawson** [comment]
we decided to revisit this in the future if we add another linear solver
