### ISSUE TITLE
Two different version of Chapman configurations coexist

### ISSUE THREAD

**Issue by boulderdaze** [NCAR/micm#368]
There are two different version of Chapman configuration, one [kpp version](https://github.com/NCAR/micm/tree/main/examples/Chapman) and the other [music box interactive version](https://github.com/NCAR/micm/tree/main/test/unit/unit_configs/chapman)

**Ideas**
- Leave the version of Chapman that is in the examples folder, because it is the most correct version
- Add a README to the `test/unit/unit_configs/` folder to indicate that all the configurations in this folder are for internal testing and should not be used for actual simulations.

**Comment by mattldawson** [comment]
I like the second idea. I think some things have been added to the Chapman mechanism in the tests that aren't scientifically correct, but are used to test specific parts of the configuration reader.

We could also rename the mechanism in the tests to something other than Chapman to make it clear that it is not really a usable configuration
