### ISSUE TITLE
Create `CudaVectorMatrix` class

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#392]
Extend the `VectorMatrix` class for use with CUDA solver functions.

Acceptance Criteria:

- `CudaVectorMatrix` class should allocate/deallocate device memory for matrix data on construction/destruction
- Matrix data is readable/writable from host and device

**Ideas**
- It might be easiest to add something like `SyncHost` and `SyncDevice` functions that would explicitly copy matrix data from device-to-host and host-to-device

**Comment by sjsprecious** [comment]
While I am working on the other CUDA functions, I find that constants like `num_of_grids` and `num_of_reactions` are used in many places. Should they become a member of this CUDA matrix class as well? Or defined somewhere else?

**Comment by sjsprecious** [comment]
Thanks Matt. That sounds a good plan. But we may need to put a note about what `column_size`, `row_size`, etc mean since their meanings could differ depending on whether it is a vector matrix, right?
