### ISSUE TITLE
Incomplete Constructor for CudaLinearSolver

### ISSUE THREAD

**Issue by mwaxmonsky** [NCAR/micm#417]
**Describe the bug**
There are two constructors for `CudaLinearSolver` in `include/micm/solver/cuda_linear_solver.hpp` one of which is missing an implementation and a template parameter list for the base `LinearSolver`:
```c++
CudaLinearSolver(
  const SparseMatrixPolicy<T>& matrix,
  T initial_value,
  const std::function<LuDecompositionPolicy(const SparseMatrixPolicy<T>&)> create_lu_decomp)
    : LinearSolver(matrix, initial_value, create_lu_decomp);
```
This causes a compiler error in certain Nvidia compilers under certain conditions (such as the `nvcc` from Nvidia's official conda package list).

**To Reproduce**
1. Create a new Conda environment 
2. `$ conda create --prefix ./nvcc-env nvidia::cuda-compiler nvidia::cuda-cccl nvidia::cuda-command-line-tools && conda activate ./nvcc-env`
3. `$ mkdir build && cd build && make all`
4. There is an error about the above mentioned constructor missing its definition and not having a template parameter list.

**Expected behavior**
The build should complete as expected.

**Screenshots**
N\A

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS

**Smartphone (please complete the following information):**
N\A

**Additional context**
N\A

**Comment by sjsprecious** [comment]
Thanks @mwaxmonsky for reporting this issue. I discussed with Matt before, and we decided to let the `CudaLinearSolver` constructors take two arguments only (simplify the interface and no worry about the lamda function), but the underlying base class would call the LuDecomposition function before we copied the constant data to the device.

I am curious about the error here. What does it look like? Which CUDA and NVHPC versions are you using?

**Comment by mattldawson** [comment]
Hi @sjsprecious and @mwaxmonsky - Just to clarify, I think it's ok to just have a 2-argument constructor for `CudaLinearSolver`, or to also have one that takes the lambda builder function. But, as @mwaxmonsky points out, the current problem is that there is a partially implemented 3-argument constructor.

My personal preference would be to also have the 3-argument constructor, for consistency, but only if someone wants to implement this.

**Comment by mattldawson** [comment]
My suggestion would be to leave that decision to whoever works on this issue.

**Comment by mwaxmonsky** [comment]
> Thanks @mwaxmonsky for reporting this issue. I discussed with Matt before, and we decided to let the `CudaLinearSolver` constructors take two arguments only (simplify the interface and no worry about the lamda function), but the underlying base class would call the LuDecomposition function before we copied the constant data to the device.
> 
> I am curious about the error here. What does it look like? Which CUDA and NVHPC versions are you using?

Unfortunately, I'm having some difficulty re-creating the issue on the on-prem cloud machines.  Not sure why but I'm trying to re-create in on my own VMs.  Once I get it working, I can add that to the issue detail above.

**Comment by mattldawson** [comment]
I like that solution, personally. It's more consistent with the other classes.
