### ISSUE TITLE
Ownership of a cublas handle

### ISSUE THREAD

**Issue by sjsprecious** [NCAR/micm#428]
Thanks to @mwaxmonsky , it turns out that the cublas handle should be associated with a pair of host thread/rank and device (see the Section `2.1.2. cuBLAS Context` at https://docs.nvidia.com/cuda/cublas/#example-code).

Currently a cublas handle is generated for each object of class `CudaVectorMatrix`. This is fine but just redundant. In addition, creating/destroying a cublas handle is way much expensive compared to calling a cublas API. Thus even if they are done in the constructor/destructor, we should still try to reduce its frequency as much as possible for the efficiency purpose.

Proposed solution (not sure if it is doable):
- Each MPI rank / OMP thread will generate a cublas handle at the beginning (even before the solver object is created), then it passes the handle to whatever function that needs it.

This issue should be treated as an optimization step and we won't worry about it until we have a multi-GPU test.

Ideas:
- Generate a singleton like the `GetInstance()` function for Jitcompiler https://github.com/NCAR/micm/blob/555be4edd17220c923e9e4ae298662c690939d81/include/micm/jit/jit_compiler.hpp#L108-L121
- In the Cuda matrix constructor, call the `GetInstance()` function instead of creating the cublas handle directly.
- Whichever the first Cuda matrix will generate the cublas handle; the rest Cuda matrices will just share the same pointer later.

**Comment by K20shores** [comment]
#488 says that we might need to make a builder class for solvers, so it's possible that the builder could handle this
