### ISSUE TITLE
Update CMakeLists.txt to support latest CUDA project type and architectures

### ISSUE THREAD

**Issue by mwaxmonsky** [NCAR/micm#546]
**Is your feature request related to a problem? Please describe.**
Current implementation hard codes sm80 so this will not be usable on v100s or h100s.

**Describe the solution you'd like**
A flag that turns on a particular version or set of supported gpu architectures.

**Describe alternatives you've considered**
N\A

**Additional context**
N\A

**Comment by sjsprecious** [comment]
I think this issue is fixed by my changes here (https://github.com/NCAR/micm/blob/428-singleton-for-cublas-handle/src/CMakeLists.txt#L55-L64) but let me know if you think it is not enough.
