### ISSUE TITLE
Move all tutorial code snippets to tests

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#557]
Some tutorial sections have embedded code snippets. These should be moved to tests so the code doesn't become stale.

**Acceptance Criteria**
- No `.rst` files in `docs/source/` contain source code

**Comment by K20shores** [comment]
The only code I can find is in https://ncar.github.io/micm/user_guide/user_defined_rate_constant_tutorial.html, but that's not code, it's a diff which we can't show without putting code into the tutorial. I vote we close this @mattldawson
