### ISSUE TITLE
MSVC build fails

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#563]
MSVC 2019 (Win32) build is failing because of ICEs, and MSVC 2022 (x64) tests are failing with a SEGFAULT.

**Acceptance Criteria**
- Tests build and pass for all MSVC cases

**Ideas**
- This failure began after merging #560 and could be related to changes made there
- The failure could also be related to recent bugs identified with the Windows base images (@mwaxmonsky - do you still have the links for these?)
- A couple ICEs for the MSVC 2019 build provided a file and line number and were able to be avoided by modifying this code:
https://github.com/NCAR/micm/blob/b819e5770cd7e83d60d23181c2a90e1bbd660afb/test/integration/oregonator.hpp#L39-L42

which had been:
```
    return SolverPolicy(
      parameters,
      LinearSolverPolicy(jacobian, 1.0e-30),
      Oregonator<MatrixPolicy, SparseMatrixPolicy>(number_of_grid_cells, nonzero_jacobian_elements),
      jacobian);
```

**Comment by mwaxmonsky** [comment]
https://github.com/actions/runner-images/issues/10020

**Comment by mattldawson** [comment]
It appears the MSVC 2022 tests are now passing, so it may have been an issue with the action runner that got fixed
