### ISSUE TITLE
Check for singularity when the solver parameters flag is turned on

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#572]
There is a flag in `RosenbrockSolverParameters` to allow checking for singularity, but it currently doesn't do anything. Check for singularity when this flag is enabled.

**Acceptance Criteria**
- A singular matrix will result in a convergence failure for the current solver time step when the `RosenbrockSolverParameters::check_singularity_` flag is `true`

**Ideas**
- Possibly add a `LinearSolver::SafeFactor()` function that checks for singularity during the factoring, and can be called here:
https://github.com/NCAR/micm/blob/e076450a72532f1c780b47fc4e16a44dd8ba5e2b/include/micm/solver/rosenbrock.inl#L262-L263
- I think checking for singularity means checking whether the denominators here:
https://github.com/NCAR/micm/blob/e076450a72532f1c780b47fc4e16a44dd8ba5e2b/include/micm/solver/linear_solver.inl#L165
and here:
https://github.com/NCAR/micm/blob/e076450a72532f1c780b47fc4e16a44dd8ba5e2b/include/micm/solver/linear_solver.inl#L181
are 0, but we should ask a math person.
- The `JitLinearSolver` and `CudaLinearSolver` could probably override `SafeFactor` and just throw a "not yet implemented" error until we decide this would be useful to implement with JIT and/or on the GPUs

**Comment by K20shores** [comment]
We already have singularity checks. They are present in the LU Decomposition, so I don't think we need to change the Factor function. But we do have to change the `LinearFactor` function in rosenbrock to actually use the singularity check that we already have
