### ISSUE TITLE
Test all solvers against Robertson tests

### ISSUE THREAD

**Issue by K20shores** [NCAR/micm#575]
All of the mentioned tests are very stiff systems.

## Acceptance Criteria
- [x] CPU Rosenbrock passes all these analytical tests (dense matrix)
- [x]  CPU Rosenbrock passes all these analytical tests (vector matrix)
- [x] CPU JIT Rosenbrock passes all these analytical tests
- [x] GPU Rosenbrock passes all these analytical tests

**Comment by K20shores** [comment]
@sjsprecious do you think it's worth testing the cuda solver against these analytical tests? We'd have to write cuda kernels fro E5, Oregonator, and HIRES

**Comment by sjsprecious** [comment]
@K20shores possibly not if they require a specific implementation of CUDA kernels. I think it is enough if we can get all the CUDA tests that are covered by the JIT tests working. This is just my two cents.

**Comment by K20shores** [comment]
@sjsprecious I'll change it to just the robertson tests then; it won't require kernels

**Comment by K20shores** [comment]
Closed by #596 when the vector tests were added to analytical policy
