### ISSUE TITLE
Check if resetting the L and U matrices before solving with Rosenbrock is needed

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#587]
Currently the lower and upper matrices on the `State` are reset to zero at the beginning of the Rosenbrock solve, but this shouldn't actually be necessary. It was likely just causing an error before the normalized error function was set to properly work with vectorizable matrices where the number of grid cells was not even divisible by the vector dimension. See if this can be removed now.

**Acceptance Criteria**
- The reseting of the lower and upper matrices at the beginning of the solve is removed or an explanation of why it is necessary is included as a comment in the code

**Comment by K20shores** [comment]
Added in [this PR](https://github.com/NCAR/micm/pull/410) (kyle can't remember why, but was doing lots of work in the performance repo at the time and some repeated calls were causing issues, maybe in the benchmarking)
