### ISSUE TITLE
Rosenbrock parameter updates

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#75]
Should the `three_stage_rosenbrock()` function be a static class function that returns a `RosenbrockSolverParameters` object that could then be modified by a user before passing it to the `RosenbrockSolver` constructor?

(But, the `N_` data member of `RosenbrockSolverParameters` should probably always be calculated based on the `System.StateSize()` and the number of grid cells, and shouldn't be editable by users.)

**Comment by K20shores** [comment]
I don't think so. Those parameters are all calculated based on the number of stages. The only reason to make them editable is if someone wanted to test out a configuration for a new number of stages that they've made
