### ISSUE TITLE
Invalid check for singular matrix

### ISSUE THREAD

**Issue by K20shores** [NCAR/micm#82]
https://github.com/NCAR/micm/blob/d0cba322a123aad462dae076962656e0e830a0ea/include/micm/solver/rosenbrock.hpp#L577C2-L585

**Comment by K20shores** [comment]
This is the original code. Line 284-286 seem to be the problem lines

https://github.com/NCAR/micm/blob/d0cba322a123aad462dae076962656e0e830a0ea/test/regression/old_micm/src/kinetics.F90#L251-L306

**Comment by mattldawson** [comment]
Stacy says that the MOZART solver in CAM-Chem does not check for singular matrices and this has never caused a problem. Maybe let's create an option in `RosenbrockSolver` to enable/disable these checks (with the default being disabled). We can then create a separate set of `Decompose` functions that checks if `U_ii` is very small before dividing by it in the last step of the algorithm and if so returns a singular matrix flag.
